# Fly.io configuration for ConstructAI Frontend
app = "constructai-frontend"
primary_region = "ord"

[build]
  dockerfile = "./deploy/Dockerfile.frontend"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://constructai-api.fly.dev"
  NEXT_PUBLIC_WS_URL = "wss://constructai-api.fly.dev/ws"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deployment]
  strategy = "canary"
