# Render.com deployment configuration for ConstructAI
services:
  # Frontend Service
  - type: web
    name: constructai-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: constructai-backend
          property: host
        value: https://constructai-backend.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://constructai-backend.onrender.com/ws

  # Backend API Gateway
  - type: web
    name: constructai-backend
    env: python
    plan: free
    region: oregon
    buildCommand: cd backend/gateway && pip install -r requirements.txt
    startCommand: cd backend/gateway && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: constructai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: constructai-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

  # User Service
  - type: web
    name: constructai-user-service
    env: python
    plan: free
    region: oregon
    buildCommand: cd backend/services/user && pip install -r requirements.txt
    startCommand: cd backend/services/user && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: constructai-db
          property: connectionString

  # Static Site (Documentation)
  - type: web
    name: constructai-docs
    env: static
    plan: free
    buildCommand: npm run build:docs
    staticPublishPath: ./docs/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: constructai-db
    databaseName: constructai
    user: admin
    plan: free

# Redis Cache
  - name: constructai-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
